---
kind: pipeline
name: default
type: docker

steps:
- name: nextcloud stable
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: stable
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=stable-fpm-alpine

- name: nextcloud latest
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: latest
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=fpm-alpine

- name: nextcloud 22
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 22
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=22-fpm-alpine

- name: nextcloud 23
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 23
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=23-fpm-alpine

- name: nextcloud 24
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 24
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=24-fpm-alpine

- name: nextcloud 25
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 25
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=25-fpm-alpine

- name: nextcloud 26
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 26
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=26-fpm-alpine

- name: nextcloud 27
  image: plugins/docker
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 27
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=27-fpm-alpine

- name: parallelism provider
  image: alpine
  when:
    branch:
    - master
  depends_on:
    - nextcloud stable
    - nextcloud latest
    - nextcloud 22
    - nextcloud 23
    - nextcloud 24
    - nextcloud 25
    - nextcloud 26
    - nextcloud 27
