---
kind: pipeline
name: default
type: docker

steps:
- name: nextcloud stable
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: stable
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=stable-fpm-alpine

- name: nextcloud latest
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: latest
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=fpm-alpine

- name: nextcloud 23
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 23
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=23-fpm-alpine

- name: nextcloud 24
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 24
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=24-fpm-alpine

- name: nextcloud 25
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 25
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=25-fpm-alpine

- name: nextcloud 26
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 26
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=26-fpm-alpine

- name: nextcloud 27
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 27
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=27-fpm-alpine

- name: nextcloud 28
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 28
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=28-fpm-alpine

- name: nextcloud 29
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 29
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=29-fpm-alpine

- name: nextcloud 30
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 30
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=30-fpm-alpine

- name: nextcloud 31
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 31
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=31-fpm-alpine

- name: parallelism provider
  image: alpine
  depends_on:
    - nextcloud stable
    - nextcloud latest
    - nextcloud 23
    - nextcloud 24
    - nextcloud 25
    - nextcloud 26
    - nextcloud 27
    - nextcloud 28
    - nextcloud 29
    - nextcloud 30
    - nextcloud 31
